//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnnualPartyAdmin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnnualPartyAdmin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 〇,ling
        ///爱,ai
        ///矮,ai
        ///挨,ai
        ///哎,ai
        ///碍,ai
        ///癌,ai
        ///唉,ai
        ///哀,ai
        ///蔼,ai
        ///皑,ai
        ///嫒,ai
        ///瑷,ai
        ///暧,ai
        ///捱,ai
        ///砹,ai
        ///嗳,ai
        ///锿,ai
        ///霭,ai
        ///伌,ai
        ///僾,ai
        ///凒,ai
        ///啀,ai
        ///嘊,ai
        ///噯,ai
        ///塧,ai
        ///壒,ai
        ///嬡,ai
        ///愛,ai
        ///懓,ai
        ///昹,ai
        ///曖,ai
        ///毐,ai
        ///溰,ai
        ///溾,ai
        ///璦,ai
        ///皚,ai
        ///皧,ai
        ///瞹,ai
        ///硋,ai
        ///薆,ai
        ///藹,ai
        ///譪,ai
        ///躷,ai
        ///鎄,ai
        ///鑀,ai
        ///靄,ai
        ///馤,ai
        ///鱫,ai
        ///鴱,ai
        ///按,an
        ///安,an
        ///暗,an
        ///岸,an
        ///案,an
        ///鞍,an
        ///氨,an
        ///铵,an
        ///桉,an
        ///黯,an
        ///侒,an
        ///儑,an
        ///唵,an
        ///啽,an
        ///垵,an
        ///堓,an
        ///峖,an
        ///盦,an
        ///盫,an
        ///罯,an
        ///腤,an
        ///荌,an
        ///萻,an
        ///蓭,an
        ///誝,an
        ///豻,an
        ///貋,an
        ///銨,an
        ///錌,an
        ///隌,an
        ///雸,an
        ///鞌,an
        ///韽,an
        ///馣,an
        ///鮟,an
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SinglePinYin {
            get {
                return ResourceManager.GetString("SinglePinYin", resourceCulture);
            }
        }
    }
}
